name: Playwright E2E Tests with Allure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*  
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm test

      - name: Generate Allure Report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      # Upload Allure HTML report
      - name: Upload Allure HTML Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      # Upload raw Allure results
      - name: Upload Allure Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30

      # Nếu bạn vẫn muốn giữ JUnit XML và Playwright HTML report
      - name: Upload JUnit XML
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml
          retention-days: 30

      - name: Upload Playwright HTML Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: reports/html
          retention-days: 30